In [1]:
#### 1. Import the numpy package under the name `np` (★☆☆)
import numpy as np

In [2]:
#### 2. Print the numpy version and the configuration (★☆☆)

print(np.__version__)
# print(np.show_config())

1.26.4


In [3]:
#### 3. Create a null vector of size 10 (★☆☆)

np.empty(shape=(10,))

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [4]:
#### 4. How to find the memory size of any array (★☆☆)

z = np.empty((10))

print(z.nbytes)
print(z.size * z.itemsize)

80
80


In [5]:
#### 5. How to get the documentation of the numpy add function from the command line? (★☆☆)

# help(np.add)

In [6]:
# np.info(np.add)

In [7]:
#### 6. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

z = np.empty((10))
z[4] = 1
z

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

In [8]:
#### 7. Create a vector with values ranging from 10 to 49 (★☆☆)

np.arange(start=10, stop=50)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

In [9]:
#### 8. Reverse a vector (first element becomes last) (★☆☆)

z[::-1]

array([0., 0., 0., 0., 0., 1., 0., 0., 0., 0.])

In [10]:
#### 9. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

np.arange(9).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [11]:
#### 10. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)

arr = np.array([1,2,0,0,4,0])

np.where(arr != 0)

(array([0, 1, 4]),)

In [12]:
#### 11. Create a 3x3 identity matrix (★☆☆)


np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [13]:
#### 12. Create a 3x3x3 array with random values (★☆☆)

np.random.random((3,3,3))

array([[[0.45851702, 0.07318341, 0.42195276],
        [0.17903427, 0.92765233, 0.4624633 ],
        [0.61193158, 0.20604385, 0.52409035]],

       [[0.37429676, 0.45913708, 0.78880483],
        [0.79015435, 0.21153471, 0.37819757],
        [0.66159218, 0.06229996, 0.70974164]],

       [[0.34335016, 0.97945575, 0.20260566],
        [0.44831195, 0.77296597, 0.70245153],
        [0.99949469, 0.08012149, 0.4599214 ]]])

In [14]:
#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)

arr = np.random.random((10,10))

arr.min(), arr.max()

(0.001642042924132503, 0.9861681723273937)

In [15]:
#### 14. Create a random vector of size 30 and find the mean value (★☆☆)

arr = np.random.random((30,))
arr.mean()

0.5969367817806256

In [16]:
#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆)

mat = np.ones((5, 5))
mat[1:-1, 1:-1] = 0
mat

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

In [17]:
#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆)

mat = np.full((5,5), 3)
mat2 = np.pad(mat, 1)
mat2

array([[0, 0, 0, 0, 0, 0, 0],
       [0, 3, 3, 3, 3, 3, 0],
       [0, 3, 3, 3, 3, 3, 0],
       [0, 3, 3, 3, 3, 3, 0],
       [0, 3, 3, 3, 3, 3, 0],
       [0, 3, 3, 3, 3, 3, 0],
       [0, 0, 0, 0, 0, 0, 0]])

In [18]:
#### 17. What is the result of the following expression? (★☆☆)

print(0 * np.nan)
print(np.nan == np.nan)
print(np.inf > np.nan)
print(np.nan - np.nan)
print(np.nan in set([np.nan]))
print(0.3 == 3 * 0.1)

nan
False
False
nan
True
False


In [19]:
#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)

np.diag([1, 2, 3, 4], k=-1)

array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0]])

In [20]:
#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)

Z = np.zeros((8,8),dtype=int)
Z[1::2,::2] = 1
Z[::2,1::2] = 1
print(Z)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [21]:
#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element? (★☆☆)


np.unravel_index(100, (6,7,8))

(1, 5, 4)

In [22]:
#### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆)

np.tile([[1,0], [0,1]], (4,4))

array([[1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1]])

In [23]:
#### 22. Normalize a 5x5 random matrix (★☆☆)

mat = np.random.random((5,5))
norm_matrix = (mat - mat.mean()) / mat.std()

norm_matrix

array([[-0.41582993, -0.9815997 ,  0.09385938,  1.48755242, -0.85311282],
       [-1.27980397,  0.36852038, -0.12610081,  0.31823155,  1.18137442],
       [ 1.73718068, -1.34879736,  0.29368517, -0.64127552, -0.22047506],
       [ 1.44529375,  1.69283247, -0.88366795, -0.97915724, -1.13562248],
       [-1.29533009, -0.17788526,  1.1911146 , -0.43992145,  0.96893483]])

In [24]:
#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆)

np.dtype(
    [
        ("r", np.ubyte),
        ("g", np.ubyte),
        ("b", np.ubyte),
        ("a", np.ubyte)
    ]
)

dtype([('r', 'u1'), ('g', 'u1'), ('b', 'u1'), ('a', 'u1')])

In [25]:
#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)

np.random.random((5, 3)) @ np.random.random((3,2))

array([[0.49756921, 0.55057636],
       [0.83221895, 1.29041898],
       [0.70611064, 0.82415443],
       [0.78872184, 1.03433646],
       [0.41145538, 0.42741142]])

In [26]:
#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

arr = np.arange(10)

arr[(3 < arr) & (arr <8)] *= -1

arr 

array([ 0,  1,  2,  3, -4, -5, -6, -7,  8,  9])

#### 26. What is the output of the following script? (★☆☆)


In [27]:
print(sum(range(5),-1))
print(np.sum(range(5),-1))

9
10


#### 27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)
```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

In [28]:
z = np.empty(10)

Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
# Z<Z>Z

array([[0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.]])

#### 28. What are the result of the following expressions? (★☆☆)

In [29]:

print(np.array(0) / np.array(0))
print(np.array(0) // np.array(0))
print(np.array([np.nan]).astype(int).astype(float))

nan
0
[0.]


/var/folders/_d/lppp9skx6dn73x36dpmmd7xc0000gn/T/ipykernel_27355/608921916.py:1: RuntimeWarning: invalid value encountered in divide
  print(np.array(0) / np.array(0))
/var/folders/_d/lppp9skx6dn73x36dpmmd7xc0000gn/T/ipykernel_27355/608921916.py:2: RuntimeWarning: divide by zero encountered in floor_divide
  print(np.array(0) // np.array(0))
/var/folders/_d/lppp9skx6dn73x36dpmmd7xc0000gn/T/ipykernel_27355/608921916.py:3: RuntimeWarning: invalid value encountered in cast
  print(np.array([np.nan]).astype(int).astype(float))


#### 29. How to round away from zero a float array ? (★☆☆)

In [30]:
Z = np.random.uniform(-10,+10,10)

print(np.copysign(np.ceil(np.abs(Z)), Z))

[ 9.  7.  1.  2. -6. -3.  6.  6. -8.  2.]


#### 30. How to find common values between two arrays? (★☆☆)

In [31]:
z1 = np.random.randint(0, 10, 10)
z2 = np.random.randint(0, 10, 10)

z1, z2, np.intersect1d(z1, z2)

(array([0, 7, 7, 7, 5, 7, 5, 7, 4, 9]),
 array([8, 8, 8, 4, 4, 8, 7, 2, 2, 4]),
 array([4, 7]))

#### 31. How to ignore all numpy warnings (not recommended)? (★☆☆)

In [32]:
# Suicide mode on
defaults = np.seterr(all="ignore")
Z = np.ones(1) / 0

# Back to sanity
_ = np.seterr(**defaults)

#### 32. Is the following expressions true? (★☆☆)

In [33]:
np.sqrt(-1) == np.emath.sqrt(-1)

/var/folders/_d/lppp9skx6dn73x36dpmmd7xc0000gn/T/ipykernel_27355/244602691.py:1: RuntimeWarning: invalid value encountered in sqrt
  np.sqrt(-1) == np.emath.sqrt(-1)


False

In [34]:
np.emath.sqrt(-1)

1j

#### 33. How to get the dates of yesterday, today and tomorrow? (★☆☆)

In [35]:
yesterday = np.datetime64('today') - np.timedelta64(1)
today     = np.datetime64('today')
tomorrow  = np.datetime64('today') + np.timedelta64(1)

print(yesterday)
print(today)
print(tomorrow)

2025-10-18
2025-10-19
2025-10-20


#### 34. How to get all the dates corresponding to the month of July 2016? (★★☆)

In [36]:
Z = np.arange('2016-07', '2016-08', dtype='datetime64[D]')
print(Z)

['2016-07-01' '2016-07-02' '2016-07-03' '2016-07-04' '2016-07-05'
 '2016-07-06' '2016-07-07' '2016-07-08' '2016-07-09' '2016-07-10'
 '2016-07-11' '2016-07-12' '2016-07-13' '2016-07-14' '2016-07-15'
 '2016-07-16' '2016-07-17' '2016-07-18' '2016-07-19' '2016-07-20'
 '2016-07-21' '2016-07-22' '2016-07-23' '2016-07-24' '2016-07-25'
 '2016-07-26' '2016-07-27' '2016-07-28' '2016-07-29' '2016-07-30'
 '2016-07-31']


#### 35. How to compute ((A+B)*(-A/2)) in place (without copy)? (★★☆)

In [37]:
A = np.ones(3)*1
B = np.ones(3)*2
np.add(A,B,out=B)
np.divide(A,2,out=A)
np.negative(A,out=A)
np.multiply(A,B,out=A)

array([-1.5, -1.5, -1.5])

#### 36. Extract the integer part of a random array of positive numbers using 4 different methods (★★☆)

In [38]:
Z = np.random.uniform(0, 10, 15)
print(Z - Z%1)
print(Z // 1)
print(np.floor(Z))
print(Z.astype(int))

[7. 1. 4. 9. 8. 1. 4. 1. 8. 9. 0. 6. 3. 6. 2.]
[7. 1. 4. 9. 8. 1. 4. 1. 8. 9. 0. 6. 3. 6. 2.]
[7. 1. 4. 9. 8. 1. 4. 1. 8. 9. 0. 6. 3. 6. 2.]
[7 1 4 9 8 1 4 1 8 9 0 6 3 6 2]


#### 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)

In [39]:
Z = np.zeros((5,5))
Z += np.arange(5)
print(Z)

[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


In [40]:
Z = np.tile(np.arange(0, 5), (5,1))
Z

array([[0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4]])

#### 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆)

In [41]:
def generate():
    for x in range(10):
        yield x
Z = np.fromiter(generate(),dtype=float,count=-1)
print(Z)

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆)

In [42]:
np.linspace(0, 1, 11, endpoint=False)[1:]

array([0.09090909, 0.18181818, 0.27272727, 0.36363636, 0.45454545,
       0.54545455, 0.63636364, 0.72727273, 0.81818182, 0.90909091])

#### 40. Create a random vector of size 10 and sort it (★★☆)

In [43]:
a = np.random.random(10)
a.sort()
a

array([0.12672412, 0.17456717, 0.43204642, 0.46280455, 0.47542825,
       0.56441089, 0.85230578, 0.87198201, 0.92375409, 0.93890974])

#### 41. How to sum a small array faster than np.sum? (★★☆)

In [44]:
Z = np.arange(10)
np.add.reduce(Z)

45

#### 42. Consider two random arrays A and B, check if they are equal (★★☆)

In [45]:
A = np.random.randint(0,2,5)
B = np.random.randint(0,2,5)

# Assuming identical shape of the arrays and a tolerance for the comparison of values
equal = np.allclose(A,B)
print(equal)

False


In [46]:
equal = np.array_equal(A,B)
print(equal)

False


#### 43. Make an array immutable (read-only) (★★☆)

In [47]:
Z = np.zeros(10)
Z.flags.writeable = False
# Z[0] = 1

#### 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆)

In [48]:
mat = np.random.random((10,2))

out = np.column_stack((
    np.hypot(mat[:, 0], mat[:, 1]),          # radius
    np.arctan2(mat[:, 1], mat[:, 0])         # angle (radians)
))

#### 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆)

In [49]:
Z = np.random.random(10)
Z[np.argmax(Z)] = 0
Z

array([0.11665051, 0.29045914, 0.45374691, 0.35722005, 0.3045012 ,
       0.35416076, 0.81003871, 0.1010137 , 0.        , 0.60757759])

#### 46. Create a structured array with `x` and `y` coordinates covering the [0,1]x[0,1] area (★★☆)

In [50]:
Z = np.zeros((5,5), [('x',float),('y',float)])
Z['x'], Z['y'] = np.meshgrid(np.linspace(0,1,5),
                             np.linspace(0,1,5))
print(Z)

[[(0.  , 0.  ) (0.25, 0.  ) (0.5 , 0.  ) (0.75, 0.  ) (1.  , 0.  )]
 [(0.  , 0.25) (0.25, 0.25) (0.5 , 0.25) (0.75, 0.25) (1.  , 0.25)]
 [(0.  , 0.5 ) (0.25, 0.5 ) (0.5 , 0.5 ) (0.75, 0.5 ) (1.  , 0.5 )]
 [(0.  , 0.75) (0.25, 0.75) (0.5 , 0.75) (0.75, 0.75) (1.  , 0.75)]
 [(0.  , 1.  ) (0.25, 1.  ) (0.5 , 1.  ) (0.75, 1.  ) (1.  , 1.  )]]


#### 47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj)) (★★☆)

In [51]:
# x = np.random.random((1,10))
# y = np.random.random((10,1))

# 1/(x - y )

X = np.arange(8)
Y = X + 0.5
C = 1.0 / np.subtract.outer(X, Y)
print(np.linalg.det(C))

3638.1636371179666


#### 48. Print the minimum and maximum representable values for each numpy scalar type (★★☆)

In [52]:
for dtype in [np.int8, np.int32, np.int64]:
   print(np.iinfo(dtype).min)
   print(np.iinfo(dtype).max)
for dtype in [np.float32, np.float64]:
   print(np.finfo(dtype).min)
   print(np.finfo(dtype).max)
   print(np.finfo(dtype).eps)

-128
127
-2147483648
2147483647
-9223372036854775808
9223372036854775807
-3.4028235e+38
3.4028235e+38
1.1920929e-07
-1.7976931348623157e+308
1.7976931348623157e+308
2.220446049250313e-16


#### 49. How to print all the values of an array? (★★☆)

In [53]:
np.set_printoptions(threshold=float("inf"))
Z = np.zeros((40,40))
print(Z)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


#### 50. How to find the closest value (to a given scalar) in a vector? (★★☆)

In [54]:
arr = np.random.random(10)

arr[np.abs(arr - 0.5 ).argmin()]

0.6191678394630936

#### 51. Create a structured array representing a position (x,y) and a color (r,g,b) (★★☆)

In [55]:
Z = np.zeros(10, [ ('position', [ ('x', float, 1),
                                  ('y', float, 1)]),
                   ('color',    [ ('r', float, 1),
                                  ('g', float, 1),
                                  ('b', float, 1)])])
print(Z)

[((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))]


/var/folders/_d/lppp9skx6dn73x36dpmmd7xc0000gn/T/ipykernel_27355/274409719.py:1: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  Z = np.zeros(10, [ ('position', [ ('x', float, 1),


#### 52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances (★★☆)

In [56]:
mat = np.random.random((100, 2))

X, Y = mat[:,0], mat[:,1]

dist = np.sqrt(
    (X[:, None] - X[None, :])**2 +
    (Y[:, None] - Y[None, :])**2
)
dist.shape

(100, 100)

#### 53. How to convert a float (32 bits) array into an integer (32 bits) array in place?

In [57]:
Z = (np.random.rand(10)*100).astype(np.float32)
Y = Z.view(np.int32)
Y[:] = Z
print(Y)

[44 83 53 39 39 73 92  1 53  3]


#### 54. How to read the following file? (★★☆)

In [58]:
from io import StringIO

# Fake file
s = StringIO('''1, 2, 3, 4, 5

                6,  ,  , 7, 8

                 ,  , 9,10,11
''')
Z = np.genfromtxt(s, delimiter=",", dtype=np.int8)
print(Z)

[[ 1  2  3  4  5]
 [ 6 -1 -1  7  8]
 [-1 -1  9 10 11]]


#### 55. What is the equivalent of enumerate for numpy arrays? (★★☆)

In [59]:
Z = np.arange(9).reshape(3,3)

for index, value in np.ndenumerate(Z):
    print(index, value)

print("V2")

for index in np.ndindex(Z.shape):
    print(index, Z[index])

(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8
V2
(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8


#### 56. Generate a generic 2D Gaussian-like array (★★☆)

In [60]:
X, Y = np.meshgrid(np.linspace(-1,1,10), np.linspace(-1,1,10))
D = np.sqrt(X*X+Y*Y)
sigma, mu = 1.0, 0.0
G = np.exp(-( (D-mu)**2 / ( 2.0 * sigma**2 ) ) )
print(G)

[[0.36787944 0.44822088 0.51979489 0.57375342 0.60279818 0.60279818
  0.57375342 0.51979489 0.44822088 0.36787944]
 [0.44822088 0.54610814 0.63331324 0.69905581 0.73444367 0.73444367
  0.69905581 0.63331324 0.54610814 0.44822088]
 [0.51979489 0.63331324 0.73444367 0.81068432 0.85172308 0.85172308
  0.81068432 0.73444367 0.63331324 0.51979489]
 [0.57375342 0.69905581 0.81068432 0.89483932 0.9401382  0.9401382
  0.89483932 0.81068432 0.69905581 0.57375342]
 [0.60279818 0.73444367 0.85172308 0.9401382  0.98773022 0.98773022
  0.9401382  0.85172308 0.73444367 0.60279818]
 [0.60279818 0.73444367 0.85172308 0.9401382  0.98773022 0.98773022
  0.9401382  0.85172308 0.73444367 0.60279818]
 [0.57375342 0.69905581 0.81068432 0.89483932 0.9401382  0.9401382
  0.89483932 0.81068432 0.69905581 0.57375342]
 [0.51979489 0.63331324 0.73444367 0.81068432 0.85172308 0.85172308
  0.81068432 0.73444367 0.63331324 0.51979489]
 [0.44822088 0.54610814 0.63331324 0.69905581 0.73444367 0.73444367
  0.69905581 0

#### 57. How to randomly place p elements in a 2D array? (★★☆)

In [61]:
n = 10
p = 3
Z = np.zeros((n,n))
np.put(Z, np.random.choice(range(n*n), p, replace=False),1)
print(Z)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


#### 58. Subtract the mean of each row of a matrix (★★☆)

In [62]:
X = np.random.rand(5, 10)

X - X.mean(axis=1, keepdims=True)

array([[-0.13622778, -0.11236433,  0.34157553,  0.20044521,  0.25962446,
        -0.20495184, -0.16726454, -0.47703181,  0.34329921, -0.04710411],
       [-0.03119201,  0.12911337, -0.15146192,  0.31226785,  0.09693665,
        -0.07171991, -0.18938879, -0.32076145, -0.23855756,  0.46476377],
       [ 0.00438794,  0.15717107,  0.44678245, -0.35491044, -0.16259077,
        -0.35212906,  0.11371199, -0.39274616,  0.02210242,  0.51822057],
       [ 0.09388435,  0.44731723, -0.34619333,  0.21128044, -0.32570422,
        -0.44309859,  0.08980576, -0.13930415, -0.08566409,  0.49767661],
       [-0.37429004,  0.15728656,  0.33949691,  0.04968739,  0.03226539,
         0.28326622, -0.18496416, -0.22486196,  0.18895406, -0.26684036]])

#### 59. How to sort an array by the nth column? (★★☆)

In [63]:
X = np.random.rand(5, 10)
X[np.argsort(X[:, 2]), :]

array([[0.38291363, 0.96991497, 0.07012695, 0.91293673, 0.57759132,
        0.63062867, 0.729842  , 0.67236481, 0.54923522, 0.97684037],
       [0.57855491, 0.17071141, 0.20929757, 0.25231328, 0.77832579,
        0.64486761, 0.57551368, 0.87311953, 0.43885544, 0.63686697],
       [0.98196267, 0.04841273, 0.32314088, 0.99053351, 0.27874234,
        0.72854879, 0.81090118, 0.0629606 , 0.53429461, 0.21185133],
       [0.99549079, 0.33862048, 0.62078383, 0.81974647, 0.37595988,
        0.99267329, 0.2578854 , 0.78272362, 0.80660191, 0.27838572],
       [0.05413212, 0.86859063, 0.84530865, 0.9574042 , 0.95423519,
        0.2993575 , 0.50470669, 0.66014514, 0.92502346, 0.29775489]])

#### 60. How to tell if a given 2D array has null columns? (★★☆)

In [64]:
# null : 0 
Z = np.random.randint(0,3,(3,10))
print((~Z.any(axis=0)).any())

# null : np.nan
Z=np.array([
    [0,1,np.nan],
    [1,2,np.nan],
    [4,5,np.nan]
])
print(np.isnan(Z).all(axis=0))

True
[False False  True]


In [65]:
np.isnan(Z).all(axis=0)

array([False, False,  True])

#### 61. Find the nearest value from a given value in an array (★★☆)

In [66]:
Z = np.random.uniform(0,1,10)
z = 0.5
m = Z.flat[np.abs(Z - z).argmin()]
print(m)

0.4434379856085442


#### 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? (★★☆)

In [67]:
A = np.arange(3).reshape(3,1)
B = np.arange(3).reshape(1,3)
it = np.nditer([A,B,None])
for x,y,z in it: z[...] = x + y
print(it.operands[2])

[[0 1 2]
 [1 2 3]
 [2 3 4]]


#### 63. Create an array class that has a name attribute (★★☆)

In [68]:
class NamedArray(np.ndarray):
    def __new__(cls, array, name="no name"):
        obj = np.asarray(array).view(cls)
        obj.name = name
        return obj
    def __array_finalize__(self, obj):
        if obj is None: return
        self.name = getattr(obj, 'name', "no name")

Z = NamedArray(np.arange(10), "range_10")
print (Z.name)

range_10


#### 64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? (★★★)

In [69]:
Z = np.ones(10)
I = np.random.randint(0,len(Z),20)
Z += np.bincount(I, minlength=len(Z))
print(Z)

[3. 2. 3. 3. 6. 4. 2. 4. 1. 2.]


#### 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? (★★★)

In [70]:
X = [1,2,3,4,5,6]
I = [1,3,9,3,4,1]
F = np.bincount(I,X)
print(F)

[0. 7. 0. 6. 5. 0. 0. 0. 0. 3.]


#### 66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors (★★☆)

In [71]:
w, h = 256, 256
I = np.random.randint(0, 4, (h, w, 3)).astype(np.ubyte)
colors = np.unique(I.reshape(-1, 3), axis=0)
n = len(colors)
print(n)

64


#### 67. Considering a four dimensions array, how to get sum over the last two axis at once? (★★★)

In [72]:
A = np.random.randint(0,10,(3,4,3,4))
mysum = A.sum(axis=(-2,-1))
print(mysum)

[[61 55 43 60]
 [61 44 34 47]
 [38 66 54 63]]


#### 68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset  indices? (★★★)

In [73]:
D = np.random.uniform(0,1,100)
S = np.random.randint(0,10,100)
D_sums = np.bincount(S, weights=D)
D_counts = np.bincount(S)
D_means = D_sums / D_counts
print(D_means)

[0.48473726 0.63842878 0.61427898 0.40520124 0.42306208 0.48996691
 0.31886769 0.43721092 0.50034601 0.50839384]


#### 69. How to get the diagonal of a dot product? (★★★)

In [74]:
A = np.random.uniform(0,1,(5,5))
B = np.random.uniform(0,1,(5,5))

np.einsum("ij,ji->i", A, B)

array([1.6708081 , 0.63237769, 1.03764143, 1.2846802 , 1.85111545])

#### 70. Consider the vector [1, 2, 3, 4, 5], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★)

In [75]:
vec = np.array([1, 2, 3, 4, 5])

n = len(vec)
ans = np.zeros((n + (n-1)*3))
ans[::4] = vec 

ans 

array([1., 0., 0., 0., 2., 0., 0., 0., 3., 0., 0., 0., 4., 0., 0., 0., 5.])

#### 71. Consider an array of dimension (5,5,3), how to multiply it by an array with dimensions (5,5)? (★★★)

In [76]:
A = np.random.random((5, 5, 3))
B = np.random.random((5,5))

np.einsum("ijk,ij->ijk", A, B)
# np.einsum("ijk,ij->ik", A, B)


# print(A * B[:,:,None])

array([[0.6375266 , 0.77605314, 1.15824964],
       [0.5888853 , 0.57142991, 1.28193521],
       [1.67030963, 2.21332883, 1.47126651],
       [0.78765758, 1.40704948, 1.85751111],
       [1.22642131, 1.25381143, 1.25337631]])

#### 72. How to swap two rows of an array? (★★★)

In [77]:
A = np.arange(16).reshape(4, -1)

A[[2,3]] = A[[3,2]]

A

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [12, 13, 14, 15],
       [ 8,  9, 10, 11]])

#### 73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the  triangles (★★★)

In [117]:
faces = np.random.randint(0, 100, (10, 3))
F = np.roll(faces.repeat(2, axis=1), -1, axis=1).reshape(-1, 2)
F = np.sort(F, axis=1)              # undirected
unique_edges = np.unique(F, axis=0) # (K, 2) without structured dtype

#### 74. Given a sorted array C that corresponds to a bincount, how to produce an array A such that np.bincount(A) == C? (★★★)

In [79]:
C = np.bincount([1,1,2,3,4,4,6])
print(C)
A = np.repeat(np.arange(len(C)), C)
print(A)

[0 2 1 1 2 0 1]
[1 1 2 3 4 4 6]


#### 75. How to compute averages using a sliding window over an array? (★★★)

In [80]:
Z = np.arange(20)
n = 3 # window size 

# 1
a = np.cumsum(Z)
a[n:] = a[n:] - a[:-n]
ans = a[n - 1:] / n
ans

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12., 13.,
       14., 15., 16., 17., 18.])

In [81]:
np.lib.stride_tricks.sliding_window_view(Z, n).mean(axis=1)

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12., 13.,
       14., 15., 16., 17., 18.])

#### 76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z[0],Z[1],Z[2]) and each subsequent row is  shifted by 1 (last row should be (Z[-3],Z[-2],Z[-1]) (★★★)

In [118]:
z = np.arange(15)
np.lib.stride_tricks.sliding_window_view(z, 3)

array([[ 0,  1,  2],
       [ 1,  2,  3],
       [ 2,  3,  4],
       [ 3,  4,  5],
       [ 4,  5,  6],
       [ 5,  6,  7],
       [ 6,  7,  8],
       [ 7,  8,  9],
       [ 8,  9, 10],
       [ 9, 10, 11],
       [10, 11, 12],
       [11, 12, 13],
       [12, 13, 14]])

In [126]:
sx = z.strides[0]
np.lib.stride_tricks.as_strided(z, shape=(13, 3), strides=(sx, sx))

array([[ 0,  1,  2],
       [ 1,  2,  3],
       [ 2,  3,  4],
       [ 3,  4,  5],
       [ 4,  5,  6],
       [ 5,  6,  7],
       [ 6,  7,  8],
       [ 7,  8,  9],
       [ 8,  9, 10],
       [ 9, 10, 11],
       [10, 11, 12],
       [11, 12, 13],
       [12, 13, 14]])

#### 77. How to negate a boolean, or to change the sign of a float inplace? (★★★)

In [83]:
Z = np.random.randint(0,2,100)
np.logical_not(Z, out=Z)

array([0, 1, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 1, 1,
       0, 0, 1, 0, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0,
       0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1,
       1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 1,
       1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1])

In [84]:
Z = np.random.uniform(-1.0,1.0,100)
np.negative(Z, out=Z)

array([ 0.41472315,  0.79334255, -0.51965441, -0.45658013, -0.93761238,
       -0.37153984, -0.33854587, -0.03106795, -0.61192266, -0.52942279,
        0.40177812, -0.35388509, -0.76336259, -0.47546563,  0.6163291 ,
       -0.90433952,  0.32942812, -0.46223809, -0.65400081, -0.65909119,
       -0.98695499,  0.04651259, -0.5150651 ,  0.49495561, -0.16647124,
        0.11963977,  0.41157785,  0.21997518, -0.48295014,  0.15181393,
        0.51794516,  0.68898572,  0.09322219, -0.90796567,  0.32901329,
       -0.66553505, -0.74265518,  0.30566002,  0.8996191 , -0.33372418,
       -0.13727816, -0.34807323,  0.46359566,  0.66853703,  0.03166785,
        0.6156619 , -0.41641653, -0.12940503, -0.05599953, -0.61961018,
       -0.12306288, -0.09038812,  0.39928299, -0.86737131,  0.93274388,
       -0.94024723,  0.58493625,  0.05527695,  0.25891384, -0.9606649 ,
       -0.57186981, -0.46778448,  0.5012492 , -0.60713217,  0.0881049 ,
        0.17484663, -0.05978084,  0.91066982,  0.96417215, -0.69

#### 78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i (P0[i],P1[i])? (★★★)

In [85]:
P0 = np.random.uniform(-10,10,(10,2))
P1 = np.random.uniform(-10,10,(10,2))
p  = np.random.uniform(-10,10,( 1,2))


diff = P1 - P0
diff2 = P0 - p 

np.abs(diff[:,0]*diff2[:,1] - diff[:,1]*diff2[:,0]) / np.linalg.norm(diff, axis=1)

array([ 2.39526954,  0.9425216 ,  1.44330618,  3.90182192,  4.80860105,
        9.4333098 ,  1.93326157, 11.48001013,  0.17232784, 10.76969985])

In [86]:
def distance_faster(P0,P1,p):
    #Author: Hemanth Pasupuleti
    #Reference: https://mathworld.wolfram.com/Point-LineDistance2-Dimensional.html

    v = P1- P0 
    v[:,[0,1]] = v[:,[1,0]]
    v[:,1]*=-1 
    norm = np.linalg.norm(v,axis=1)   
    r = P0 - p
    d = np.abs(np.einsum("ij,ij->i",r,v)) / norm 

    return d

print(distance_faster(P0, P1, p))

[ 2.39526954  0.9425216   1.44330618  3.90182192  4.80860105  9.4333098
  1.93326157 11.48001013  0.17232784 10.76969985]


#### 79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P[j]) to each line i (P0[i],P1[i])? (★★★)

In [87]:
P0 = np.random.uniform(-10,10,(10,2))
P1 = np.random.uniform(-10,10,(10,2))
p  = np.random.uniform(-10,10,( 15,2))

diff = P1 - P0 
diff2 = P0[:, None, :] - p[None, :, :]
diff2.shape

ans = np.abs(diff[:,0][:, None] * diff2[:, :, 1] - diff[:, 1][:, None] * diff2[:, :, 0]) / np.linalg.norm(diff, axis=1, keepdims=True)

In [88]:
def distance_points_to_lines(p: np.ndarray, p_1: np.ndarray, p_2: np.ndarray) -> np.ndarray:
    x_0, y_0 = p.T  # Shape -> (n points, )
    x_1, y_1 = p_1.T  # Shape -> (n lines, )
    x_2, y_2 = p_2.T  # Shape -> (n lines, )

    # Displacement vector coordinates from p_1 -> p_2
    dx = x_2 - x_1  # Shape -> (n lines, )
    dy = y_2 - y_1  # Shape -> (n lines, )

    # The 'cross product' term
    cross_term = x_2 * y_1 - y_2 * x_1  # Shape -> (n lines, )

    # Broadcast x_0, y_0 (n points, 1) and dx, dy, cross_term (1, n lines) -> (n points, n lines)
    numerator = np.abs(
        dy[np.newaxis, :] * x_0[:, np.newaxis]
        - dx[np.newaxis, :] * y_0[:, np.newaxis]
        + cross_term[np.newaxis, :]
    )
    denominator = np.sqrt(dx**2 + dy**2)  # Shape -> (n lines, )

    # Shape (n points, n lines) / (1, n_lines) -> (n points, n lines)
    return numerator / denominator[np.newaxis, :]

In [89]:
np.allclose(ans.T, distance_points_to_lines(p, P0, P1))

True

#### 80. Consider an arbitrary array, write a function that extracts a subpart with a fixed shape and centered on a given element (pad with a `fill` value when necessary) (★★★)

#### 81. Consider an array Z = [1,2,3,4,5,6,7,8,9,10,11,12,13,14], how to generate an array R = [[1,2,3,4], [2,3,4,5], [3,4,5,6], ..., [11,12,13,14]]? (★★★)

In [90]:
Z = [1,2,3,4,5,6,7,8,9,10,11,12,13,14]

np.lib.stride_tricks.sliding_window_view(Z, 4)

array([[ 1,  2,  3,  4],
       [ 2,  3,  4,  5],
       [ 3,  4,  5,  6],
       [ 4,  5,  6,  7],
       [ 5,  6,  7,  8],
       [ 6,  7,  8,  9],
       [ 7,  8,  9, 10],
       [ 8,  9, 10, 11],
       [ 9, 10, 11, 12],
       [10, 11, 12, 13],
       [11, 12, 13, 14]])

#### 82. Compute a matrix rank (★★★)

In [91]:
Z = np.random.random((1000,1000))
np.linalg.matrix_rank(Z)

1000

#### 83. How to find the most frequent value in an array?

In [92]:
Z = np.random.randint(0,10,50)
print(np.bincount(Z).argmax())

2


#### 84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix (★★★)

In [93]:
Z = np.arange(10*10).reshape(10,-1)

np.lib.stride_tricks.sliding_window_view(Z, (3,3))

array([[[[ 0,  1,  2],
         [10, 11, 12],
         [20, 21, 22]],

        [[ 1,  2,  3],
         [11, 12, 13],
         [21, 22, 23]],

        [[ 2,  3,  4],
         [12, 13, 14],
         [22, 23, 24]],

        [[ 3,  4,  5],
         [13, 14, 15],
         [23, 24, 25]],

        [[ 4,  5,  6],
         [14, 15, 16],
         [24, 25, 26]],

        [[ 5,  6,  7],
         [15, 16, 17],
         [25, 26, 27]],

        [[ 6,  7,  8],
         [16, 17, 18],
         [26, 27, 28]],

        [[ 7,  8,  9],
         [17, 18, 19],
         [27, 28, 29]]],


       [[[10, 11, 12],
         [20, 21, 22],
         [30, 31, 32]],

        [[11, 12, 13],
         [21, 22, 23],
         [31, 32, 33]],

        [[12, 13, 14],
         [22, 23, 24],
         [32, 33, 34]],

        [[13, 14, 15],
         [23, 24, 25],
         [33, 34, 35]],

        [[14, 15, 16],
         [24, 25, 26],
         [34, 35, 36]],

        [[15, 16, 17],
         [25, 26, 27],
         [35, 36, 37]],

    

#### 85. Create a 2D array subclass such that Z[i,j] == Z[j,i] (★★★)

#### 86. Consider a set of p matrices with shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1)) (★★★)

In [94]:
p = 68
n = 6

M = np.random.random((p,n,n))
V = np.random.random((p,n,1))

S = np.einsum('pij,pjk->ik', M, V)
print(S)

[[104.91684914]
 [107.6330365 ]
 [104.06504145]
 [ 98.99054211]
 [ 98.75330449]
 [102.56148929]]


In [95]:
S = np.tensordot(M, V, axes=[[0, 2], [0, 1]])
print(S)

[[104.91684914]
 [107.6330365 ]
 [104.06504145]
 [ 98.99054211]
 [ 98.75330449]
 [102.56148929]]


#### 87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)? (★★★)

In [96]:
Z = np.ones((16,16))

s0, s1 = Z.strides  # byte strides along each axis
Z_blocks = np.lib.stride_tricks.as_strided(
    Z,
    shape=(4, 4, 4, 4),          # (tiles_y, tiles_x, block_y, block_x)
    strides=(4*s0, 4*s1, s0, s1) # move 4 rows or cols between tiles
)

Z_blocks.sum((-2,-1))

array([[16., 16., 16., 16.],
       [16., 16., 16., 16.],
       [16., 16., 16., 16.],
       [16., 16., 16., 16.]])

#### 88. How to implement the Game of Life using numpy arrays? (★★★)


#### 89. How to get the n largest values of an array (★★★)

In [97]:
Z = np.arange(10000)
np.random.shuffle(Z)
n = 5

print (Z[np.argsort(Z)[-n:]])

[9995 9996 9997 9998 9999]


#### 90. Given an arbitrary number of vectors, build the cartesian product (every combination of every item) (★★★)

In [98]:
arrays = ([1, 2, 3], [4, 5], [6, 7])
arrays = [np.asarray(a) for a in arrays]
shape = (len(x) for x in arrays)
ix = np.indices(shape, dtype=int)
ix = ix.reshape(len(arrays), -1).T
for n, arr in enumerate(arrays):
    ix[:, n] = arrays[n][ix[:, n]]

ix

array([[1, 4, 6],
       [1, 4, 7],
       [1, 5, 6],
       [1, 5, 7],
       [2, 4, 6],
       [2, 4, 7],
       [2, 5, 6],
       [2, 5, 7],
       [3, 4, 6],
       [3, 4, 7],
       [3, 5, 6],
       [3, 5, 7]])

#### 91. How to create a record array from a regular array? (★★★)

#### 92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods (★★★)

In [99]:
x = np.random.rand(int(5e7))

%timeit np.power(x,3)
%timeit x*x*x
%timeit np.einsum('i,i,i->i',x,x,x)

340 ms ± 8.59 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
54.9 ms ± 499 μs per loop (mean ± std. dev. of 7 runs, 10 loops each)
61.3 ms ± 4.57 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


#### 93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B? (★★★)

In [127]:
a = np.arange(10)

b = np.array([2,3, 15])


a[:, None] == b


# # A: (N, D), B: (M, K)
# eq = (A[:, None, :, None] == B[None, :, None, :])  # shape (N, M, D, K)
# mask = eq.any(axis=2).all(axis=2)                  # (N, M)
# # mask[n, m] == True if A[n] contains all of B[m]

array([[False, False, False],
       [False, False, False],
       [ True, False, False],
       [False,  True, False],
       [False, False, False],
       [False, False, False],
       [False, False, False],
       [False, False, False],
       [False, False, False],
       [False, False, False]])

In [101]:
A = np.random.randint(0,5,(8,3))
B = np.random.randint(0,5,(2,2))

C = (A[..., np.newaxis, np.newaxis] == B)
# rows = np.where(C.any((3,1)).all(1))[0]
# print(rows)

In [102]:
C.shape

(8, 3, 2, 2)

In [103]:
C.any((3,1))

array([[False, False],
       [ True, False],
       [False, False],
       [ True, False],
       [ True,  True],
       [ True,  True],
       [False, False],
       [ True, False]])

#### 94. Considering a 10x3 matrix, extract rows with unequal values (e.g. [2,2,3]) (★★★)

In [104]:
Z = np.random.randint(0,5,(10,3))


print(Z[np.all(Z[:, 1:] != Z[:, :-1], axis=1), :])
print("---")
print(Z[np.all(Z[:, 1:] == Z[:, :-1], axis=1), :])

[[3 1 0]
 [4 2 3]
 [2 3 4]
 [4 0 1]
 [3 2 3]
 [1 3 1]]
---
[[4 4 4]]


#### 95. Convert a vector of ints into a matrix binary representation (★★★)

#### 96. Given a two dimensional array, how to extract unique rows? (★★★)

In [105]:
Z = np.random.randint(0,2,(6,3))
np.unique(Z, axis=0)

array([[0, 1, 1],
       [1, 0, 0],
       [1, 1, 0],
       [1, 1, 1]])

#### 97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function (★★★)

http://ajcr.net/Basic-guide-to-einsum/

In [106]:
A = np.random.uniform(0,1,10)
B = np.random.uniform(0,1,10)

np.einsum('i->', A)       # np.sum(A)
np.einsum('i,i->i', A, B) # A * B
np.einsum('i,i', A, B)    # np.inner(A, B)
np.einsum('i,j->ij', A, B)    # np.outer(A, B)

array([[0.03378109, 0.14139826, 0.33121578, 0.27937299, 0.30187369,
        0.39369713, 0.43176602, 0.56442651, 0.41780624, 0.11723026],
       [0.005005  , 0.02094952, 0.04907282, 0.04139181, 0.0447255 ,
        0.05833004, 0.06397031, 0.08362524, 0.06190203, 0.0173688 ],
       [0.0370013 , 0.15487715, 0.36278915, 0.30600441, 0.33065001,
        0.43122659, 0.47292441, 0.61823087, 0.45763391, 0.12840531],
       [0.02355311, 0.09858679, 0.23093283, 0.1947866 , 0.21047471,
        0.27449657, 0.30103925, 0.39353383, 0.29130611, 0.08173619],
       [0.04145929, 0.17353706, 0.40649871, 0.34287243, 0.37048737,
        0.48318162, 0.52990329, 0.69271655, 0.51277056, 0.14387584],
       [0.02749994, 0.11510713, 0.26963059, 0.22742728, 0.24574427,
        0.32049436, 0.35148484, 0.45947888, 0.3401207 , 0.09543284],
       [0.02585104, 0.10820525, 0.25346341, 0.21379063, 0.23100933,
        0.30127737, 0.33040965, 0.43192831, 0.31972691, 0.08971065],
       [0.02927874, 0.12255265, 0.2870712