In [260]:
#### 1. Import the numpy package under the name `np` (★☆☆)
import numpy as np

In [261]:
#### 2. Print the numpy version and the configuration (★☆☆)

print(np.__version__)
# print(np.show_config())

1.26.4


In [262]:
#### 3. Create a null vector of size 10 (★☆☆)

np.empty(shape=(10,))

array([0.45084155, 0.25290816, 0.11410866, 0.02722112, 0.01816998,
       0.03264426, 0.04815478, 0.15579439, 0.71256509, 0.23601121])

In [263]:
#### 4. How to find the memory size of any array (★☆☆)

z = np.empty((10))

print(z.nbytes)
print(z.size * z.itemsize)

80
80


In [264]:
#### 5. How to get the documentation of the numpy add function from the command line? (★☆☆)

# help(np.add)

In [265]:
# np.info(np.add)

In [266]:
#### 6. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

z = np.empty((10))
z[4] = 1
z

array([0.45084155, 0.25290816, 0.11410866, 0.02722112, 1.        ,
       0.03264426, 0.04815478, 0.15579439, 0.71256509, 0.23601121])

In [267]:
#### 7. Create a vector with values ranging from 10 to 49 (★☆☆)

np.arange(start=10, stop=50)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

In [268]:
#### 8. Reverse a vector (first element becomes last) (★☆☆)

z[::-1]

array([0.23601121, 0.71256509, 0.15579439, 0.04815478, 0.03264426,
       1.        , 0.02722112, 0.11410866, 0.25290816, 0.45084155])

In [269]:
#### 9. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

np.arange(9).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [270]:
#### 10. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)

arr = np.array([1,2,0,0,4,0])

np.where(arr != 0)

(array([0, 1, 4]),)

In [271]:
#### 11. Create a 3x3 identity matrix (★☆☆)


np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [272]:
#### 12. Create a 3x3x3 array with random values (★☆☆)

np.random.random((3,3,3))

array([[[0.90661818, 0.36671021, 0.03408091],
        [0.62905055, 0.96668326, 0.24510746],
        [0.18536171, 0.50125393, 0.45486263]],

       [[0.57799614, 0.65294426, 0.42035012],
        [0.25937841, 0.90164023, 0.94170842],
        [0.93930588, 0.55650123, 0.0934022 ]],

       [[0.04715118, 0.96122365, 0.22913906],
        [0.8703118 , 0.35344828, 0.70698971],
        [0.65794641, 0.49609547, 0.49650425]]])

In [273]:
#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)

arr = np.random.random((10,10))

arr.min(), arr.max()

(0.023010565407030392, 0.998717131580837)

In [274]:
#### 14. Create a random vector of size 30 and find the mean value (★☆☆)

arr = np.random.random((30,))
arr.mean()

0.4612343701124912

In [275]:
#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆)

mat = np.ones((5, 5))
mat[1:-1, 1:-1] = 0
mat

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

In [276]:
#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆)

mat = np.full((5,5), 3)
mat2 = np.pad(mat, 1)
mat2

array([[0, 0, 0, 0, 0, 0, 0],
       [0, 3, 3, 3, 3, 3, 0],
       [0, 3, 3, 3, 3, 3, 0],
       [0, 3, 3, 3, 3, 3, 0],
       [0, 3, 3, 3, 3, 3, 0],
       [0, 3, 3, 3, 3, 3, 0],
       [0, 0, 0, 0, 0, 0, 0]])

In [277]:
#### 17. What is the result of the following expression? (★☆☆)

print(0 * np.nan)
print(np.nan == np.nan)
print(np.inf > np.nan)
print(np.nan - np.nan)
print(np.nan in set([np.nan]))
print(0.3 == 3 * 0.1)

nan
False
False
nan
True
False


In [278]:
#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)

np.diag([1, 2, 3, 4], k=-1)

array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0]])

In [279]:
#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)

Z = np.zeros((8,8),dtype=int)
Z[1::2,::2] = 1
Z[::2,1::2] = 1
print(Z)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [280]:
#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element? (★☆☆)


np.unravel_index(100, (6,7,8))

(1, 5, 4)

In [281]:
#### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆)

np.tile([[1,0], [0,1]], (4,4))

array([[1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1]])

In [282]:
#### 22. Normalize a 5x5 random matrix (★☆☆)

mat = np.random.random((5,5))
norm_matrix = (mat - mat.mean()) / mat.std()

norm_matrix

array([[ 0.30189046,  0.00990661,  1.21876833,  0.93635269, -1.5039121 ],
       [-0.68778119,  1.22340112,  0.66015554,  0.95852175, -0.82044087],
       [-2.15916165,  0.2177155 ,  1.2463468 , -0.76207826,  1.50776891],
       [-0.51367884,  0.08304834, -0.1958545 ,  1.01113627, -1.07689543],
       [-0.47889146,  1.21085946, -1.45859448, -0.92535183, -0.00323117]])

In [283]:
#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆)

np.dtype(
    [
        ("r", np.ubyte),
        ("g", np.ubyte),
        ("b", np.ubyte),
        ("a", np.ubyte)
    ]
)

dtype([('r', 'u1'), ('g', 'u1'), ('b', 'u1'), ('a', 'u1')])

In [284]:
#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)

np.random.random((5, 3)) @ np.random.random((3,2))

array([[0.68919435, 0.95288607],
       [0.48824835, 0.70420757],
       [0.5776662 , 0.76999552],
       [0.71209455, 0.97933796],
       [0.93206193, 1.23925253]])

In [285]:
#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

arr = np.arange(10)

arr[(3 < arr) & (arr <8)] *= -1

arr 

array([ 0,  1,  2,  3, -4, -5, -6, -7,  8,  9])

#### 26. What is the output of the following script? (★☆☆)


In [286]:
print(sum(range(5),-1))
print(np.sum(range(5),-1))

9
10


#### 27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)
```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

In [287]:
z = np.empty(10)

Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
# Z<Z>Z

array([[0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.]])

#### 28. What are the result of the following expressions? (★☆☆)

In [288]:

print(np.array(0) / np.array(0))
print(np.array(0) // np.array(0))
print(np.array([np.nan]).astype(int).astype(float))

nan
0
[0.]


/var/folders/_d/lppp9skx6dn73x36dpmmd7xc0000gn/T/ipykernel_16008/608921916.py:1: RuntimeWarning: invalid value encountered in divide
  print(np.array(0) / np.array(0))
/var/folders/_d/lppp9skx6dn73x36dpmmd7xc0000gn/T/ipykernel_16008/608921916.py:2: RuntimeWarning: divide by zero encountered in floor_divide
  print(np.array(0) // np.array(0))
/var/folders/_d/lppp9skx6dn73x36dpmmd7xc0000gn/T/ipykernel_16008/608921916.py:3: RuntimeWarning: invalid value encountered in cast
  print(np.array([np.nan]).astype(int).astype(float))


#### 29. How to round away from zero a float array ? (★☆☆)

In [289]:
Z = np.random.uniform(-10,+10,10)

print(np.copysign(np.ceil(np.abs(Z)), Z))

[ 6.  6. -6. -2. -9. -2. -6. -6.  7.  7.]


#### 30. How to find common values between two arrays? (★☆☆)

In [290]:
z1 = np.random.randint(0, 10, 10)
z2 = np.random.randint(0, 10, 10)

z1, z2, np.intersect1d(z1, z2)

(array([6, 5, 7, 5, 4, 2, 6, 6, 0, 5]),
 array([1, 7, 7, 1, 9, 8, 3, 1, 2, 7]),
 array([2, 7]))

#### 31. How to ignore all numpy warnings (not recommended)? (★☆☆)

In [291]:
# Suicide mode on
defaults = np.seterr(all="ignore")
Z = np.ones(1) / 0

# Back to sanity
_ = np.seterr(**defaults)

#### 32. Is the following expressions true? (★☆☆)

In [292]:
np.sqrt(-1) == np.emath.sqrt(-1)

/var/folders/_d/lppp9skx6dn73x36dpmmd7xc0000gn/T/ipykernel_16008/244602691.py:1: RuntimeWarning: invalid value encountered in sqrt
  np.sqrt(-1) == np.emath.sqrt(-1)


False

In [293]:
np.emath.sqrt(-1)

1j

#### 33. How to get the dates of yesterday, today and tomorrow? (★☆☆)

In [294]:
yesterday = np.datetime64('today') - np.timedelta64(1)
today     = np.datetime64('today')
tomorrow  = np.datetime64('today') + np.timedelta64(1)

print(yesterday)
print(today)
print(tomorrow)

2025-10-12
2025-10-13
2025-10-14


#### 34. How to get all the dates corresponding to the month of July 2016? (★★☆)

In [295]:
Z = np.arange('2016-07', '2016-08', dtype='datetime64[D]')
print(Z)

['2016-07-01' '2016-07-02' '2016-07-03' '2016-07-04' '2016-07-05'
 '2016-07-06' '2016-07-07' '2016-07-08' '2016-07-09' '2016-07-10'
 '2016-07-11' '2016-07-12' '2016-07-13' '2016-07-14' '2016-07-15'
 '2016-07-16' '2016-07-17' '2016-07-18' '2016-07-19' '2016-07-20'
 '2016-07-21' '2016-07-22' '2016-07-23' '2016-07-24' '2016-07-25'
 '2016-07-26' '2016-07-27' '2016-07-28' '2016-07-29' '2016-07-30'
 '2016-07-31']


#### 35. How to compute ((A+B)*(-A/2)) in place (without copy)? (★★☆)

In [296]:
A = np.ones(3)*1
B = np.ones(3)*2
np.add(A,B,out=B)
np.divide(A,2,out=A)
np.negative(A,out=A)
np.multiply(A,B,out=A)

array([-1.5, -1.5, -1.5])

#### 36. Extract the integer part of a random array of positive numbers using 4 different methods (★★☆)

In [297]:
Z = np.random.uniform(0, 10, 15)
print(Z - Z%1)
print(Z // 1)
print(np.floor(Z))
print(Z.astype(int))

[3. 7. 9. 8. 1. 1. 8. 4. 0. 4. 7. 6. 4. 9. 2.]
[3. 7. 9. 8. 1. 1. 8. 4. 0. 4. 7. 6. 4. 9. 2.]
[3. 7. 9. 8. 1. 1. 8. 4. 0. 4. 7. 6. 4. 9. 2.]
[3 7 9 8 1 1 8 4 0 4 7 6 4 9 2]


#### 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)

In [298]:
Z = np.zeros((5,5))
Z += np.arange(5)
print(Z)

[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


In [299]:
Z = np.tile(np.arange(0, 5), (5,1))
Z

array([[0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4]])

#### 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆)

In [300]:
def generate():
    for x in range(10):
        yield x
Z = np.fromiter(generate(),dtype=float,count=-1)
print(Z)

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆)

In [301]:
np.linspace(0, 1, 11, endpoint=False)[1:]

array([0.09090909, 0.18181818, 0.27272727, 0.36363636, 0.45454545,
       0.54545455, 0.63636364, 0.72727273, 0.81818182, 0.90909091])

#### 40. Create a random vector of size 10 and sort it (★★☆)

In [302]:
a = np.random.random(10)
a.sort()
a

array([0.05432947, 0.26821181, 0.39122011, 0.42915847, 0.49036258,
       0.49283902, 0.50569549, 0.54800683, 0.85868963, 0.87708548])

#### 41. How to sum a small array faster than np.sum? (★★☆)

In [303]:
Z = np.arange(10)
np.add.reduce(Z)

45

#### 42. Consider two random arrays A and B, check if they are equal (★★☆)

In [304]:
A = np.random.randint(0,2,5)
B = np.random.randint(0,2,5)

# Assuming identical shape of the arrays and a tolerance for the comparison of values
equal = np.allclose(A,B)
print(equal)

False


In [305]:
equal = np.array_equal(A,B)
print(equal)

False


#### 43. Make an array immutable (read-only) (★★☆)

In [306]:
Z = np.zeros(10)
Z.flags.writeable = False
# Z[0] = 1

#### 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆)

In [307]:
mat = np.random.random((10,2))

out = np.column_stack((
    np.hypot(mat[:, 0], mat[:, 1]),          # radius
    np.arctan2(mat[:, 1], mat[:, 0])         # angle (radians)
))

#### 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆)

In [308]:
Z = np.random.random(10)
Z[np.argmax(Z)] = 0
Z

array([0.        , 0.59064506, 0.51623801, 0.52870513, 0.16868069,
       0.45303163, 0.65726633, 0.15389327, 0.15895703, 0.45267813])

#### 46. Create a structured array with `x` and `y` coordinates covering the [0,1]x[0,1] area (★★☆)

In [309]:
Z = np.zeros((5,5), [('x',float),('y',float)])
Z['x'], Z['y'] = np.meshgrid(np.linspace(0,1,5),
                             np.linspace(0,1,5))
print(Z)

[[(0.  , 0.  ) (0.25, 0.  ) (0.5 , 0.  ) (0.75, 0.  ) (1.  , 0.  )]
 [(0.  , 0.25) (0.25, 0.25) (0.5 , 0.25) (0.75, 0.25) (1.  , 0.25)]
 [(0.  , 0.5 ) (0.25, 0.5 ) (0.5 , 0.5 ) (0.75, 0.5 ) (1.  , 0.5 )]
 [(0.  , 0.75) (0.25, 0.75) (0.5 , 0.75) (0.75, 0.75) (1.  , 0.75)]
 [(0.  , 1.  ) (0.25, 1.  ) (0.5 , 1.  ) (0.75, 1.  ) (1.  , 1.  )]]


#### 47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj)) (★★☆)

In [310]:
# x = np.random.random((1,10))
# y = np.random.random((10,1))

# 1/(x - y )

X = np.arange(8)
Y = X + 0.5
C = 1.0 / np.subtract.outer(X, Y)
print(np.linalg.det(C))

3638.1636371179666


#### 48. Print the minimum and maximum representable values for each numpy scalar type (★★☆)

In [311]:
for dtype in [np.int8, np.int32, np.int64]:
   print(np.iinfo(dtype).min)
   print(np.iinfo(dtype).max)
for dtype in [np.float32, np.float64]:
   print(np.finfo(dtype).min)
   print(np.finfo(dtype).max)
   print(np.finfo(dtype).eps)

-128
127
-2147483648
2147483647
-9223372036854775808
9223372036854775807
-3.4028235e+38
3.4028235e+38
1.1920929e-07
-1.7976931348623157e+308
1.7976931348623157e+308
2.220446049250313e-16


#### 49. How to print all the values of an array? (★★☆)

In [312]:
np.set_printoptions(threshold=float("inf"))
Z = np.zeros((40,40))
print(Z)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


#### 50. How to find the closest value (to a given scalar) in a vector? (★★☆)

In [313]:
arr = np.random.random(10)

arr[np.abs(arr - 0.5 ).argmin()]

0.5692197288366689

#### 51. Create a structured array representing a position (x,y) and a color (r,g,b) (★★☆)

In [314]:
Z = np.zeros(10, [ ('position', [ ('x', float, 1),
                                  ('y', float, 1)]),
                   ('color',    [ ('r', float, 1),
                                  ('g', float, 1),
                                  ('b', float, 1)])])
print(Z)

[((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))]


/var/folders/_d/lppp9skx6dn73x36dpmmd7xc0000gn/T/ipykernel_16008/274409719.py:1: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  Z = np.zeros(10, [ ('position', [ ('x', float, 1),


#### 52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances (★★☆)

In [315]:
mat = np.random.random((100, 2))

X, Y = mat[:,0], mat[:,1]

dist = np.sqrt(
    (X[:, None] - X[None, :])**2 +
    (Y[:, None] - Y[None, :])**2
)
dist.shape

(100, 100)

#### 53. How to convert a float (32 bits) array into an integer (32 bits) array in place?

In [316]:
Z = (np.random.rand(10)*100).astype(np.float32)
Y = Z.view(np.int32)
Y[:] = Z
print(Y)

[24 93 17 57 19 32 79 32 95 55]


#### 54. How to read the following file? (★★☆)

In [317]:
from io import StringIO

# Fake file
s = StringIO('''1, 2, 3, 4, 5

                6,  ,  , 7, 8

                 ,  , 9,10,11
''')
Z = np.genfromtxt(s, delimiter=",", dtype=np.int8)
print(Z)

[[ 1  2  3  4  5]
 [ 6 -1 -1  7  8]
 [-1 -1  9 10 11]]


#### 55. What is the equivalent of enumerate for numpy arrays? (★★☆)

In [318]:
Z = np.arange(9).reshape(3,3)

for index, value in np.ndenumerate(Z):
    print(index, value)

print("V2")

for index in np.ndindex(Z.shape):
    print(index, Z[index])

(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8
V2
(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8


#### 56. Generate a generic 2D Gaussian-like array (★★☆)

In [319]:
X, Y = np.meshgrid(np.linspace(-1,1,10), np.linspace(-1,1,10))
D = np.sqrt(X*X+Y*Y)
sigma, mu = 1.0, 0.0
G = np.exp(-( (D-mu)**2 / ( 2.0 * sigma**2 ) ) )
print(G)

[[0.36787944 0.44822088 0.51979489 0.57375342 0.60279818 0.60279818
  0.57375342 0.51979489 0.44822088 0.36787944]
 [0.44822088 0.54610814 0.63331324 0.69905581 0.73444367 0.73444367
  0.69905581 0.63331324 0.54610814 0.44822088]
 [0.51979489 0.63331324 0.73444367 0.81068432 0.85172308 0.85172308
  0.81068432 0.73444367 0.63331324 0.51979489]
 [0.57375342 0.69905581 0.81068432 0.89483932 0.9401382  0.9401382
  0.89483932 0.81068432 0.69905581 0.57375342]
 [0.60279818 0.73444367 0.85172308 0.9401382  0.98773022 0.98773022
  0.9401382  0.85172308 0.73444367 0.60279818]
 [0.60279818 0.73444367 0.85172308 0.9401382  0.98773022 0.98773022
  0.9401382  0.85172308 0.73444367 0.60279818]
 [0.57375342 0.69905581 0.81068432 0.89483932 0.9401382  0.9401382
  0.89483932 0.81068432 0.69905581 0.57375342]
 [0.51979489 0.63331324 0.73444367 0.81068432 0.85172308 0.85172308
  0.81068432 0.73444367 0.63331324 0.51979489]
 [0.44822088 0.54610814 0.63331324 0.69905581 0.73444367 0.73444367
  0.69905581 0

#### 57. How to randomly place p elements in a 2D array? (★★☆)

In [320]:
n = 10
p = 3
Z = np.zeros((n,n))
np.put(Z, np.random.choice(range(n*n), p, replace=False),1)
print(Z)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


#### 58. Subtract the mean of each row of a matrix (★★☆)

In [321]:
X = np.random.rand(5, 10)

X - X.mean(axis=1, keepdims=True)

array([[ 0.13032309,  0.21958824, -0.31374319,  0.39537669, -0.15161744,
        -0.25247785,  0.08802674, -0.39255142, -0.09013491,  0.36721005],
       [-0.35539353,  0.44582269,  0.41179865, -0.21689819,  0.22055006,
         0.01152886,  0.26071041, -0.19857889, -0.44796468, -0.13157539],
       [ 0.19528671, -0.09250083,  0.15335044, -0.22789884, -0.06636758,
         0.11893693, -0.16014589,  0.07475976,  0.06138739, -0.05680809],
       [ 0.39527701,  0.24908631, -0.51100047, -0.22656753, -0.23274629,
        -0.08445085, -0.13083667,  0.19603538,  0.24962452,  0.09557861],
       [ 0.25672082, -0.49576666,  0.394004  ,  0.36008496, -0.43532197,
         0.38026042,  0.18186746, -0.52144921, -0.39975666,  0.27935683]])

#### 59. How to sort an array by the nth column? (★★☆)

In [322]:
X = np.random.rand(5, 10)
X[np.argsort(X[:, 2]), :]

array([[0.3958233 , 0.96438001, 0.18071831, 0.06197441, 0.95204271,
        0.24999493, 0.41213213, 0.97346196, 0.31022484, 0.71779241],
       [0.32727597, 0.98518466, 0.26708787, 0.35011628, 0.89842075,
        0.48290587, 0.4404205 , 0.86618223, 0.62335403, 0.25794691],
       [0.58374972, 0.37887174, 0.43055294, 0.92984934, 0.00876653,
        0.26298405, 0.69446798, 0.75915961, 0.09333531, 0.09888278],
       [0.31896614, 0.1758916 , 0.89660136, 0.5837744 , 0.50855375,
        0.41942243, 0.1852396 , 0.55993868, 0.80492485, 0.62513205],
       [0.30266162, 0.76766722, 0.90424315, 0.91510423, 0.82126352,
        0.76470984, 0.08090153, 0.86162773, 0.02161635, 0.253914  ]])

#### 60. How to tell if a given 2D array has null columns? (★★☆)

In [323]:
# null : 0 
Z = np.random.randint(0,3,(3,10))
print((~Z.any(axis=0)).any())

# null : np.nan
Z=np.array([
    [0,1,np.nan],
    [1,2,np.nan],
    [4,5,np.nan]
])
print(np.isnan(Z).all(axis=0))

True
[False False  True]


In [324]:
np.isnan(Z).all(axis=0)

array([False, False,  True])

#### 61. Find the nearest value from a given value in an array (★★☆)

In [325]:
Z = np.random.uniform(0,1,10)
z = 0.5
m = Z.flat[np.abs(Z - z).argmin()]
print(m)

0.5023097961482781


#### 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? (★★☆)

In [326]:
A = np.arange(3).reshape(3,1)
B = np.arange(3).reshape(1,3)
it = np.nditer([A,B,None])
for x,y,z in it: z[...] = x + y
print(it.operands[2])

[[0 1 2]
 [1 2 3]
 [2 3 4]]


#### 63. Create an array class that has a name attribute (★★☆)

In [327]:
class NamedArray(np.ndarray):
    def __new__(cls, array, name="no name"):
        obj = np.asarray(array).view(cls)
        obj.name = name
        return obj
    def __array_finalize__(self, obj):
        if obj is None: return
        self.name = getattr(obj, 'name', "no name")

Z = NamedArray(np.arange(10), "range_10")
print (Z.name)

range_10


#### 64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? (★★★)

In [328]:
Z = np.ones(10)
I = np.random.randint(0,len(Z),20)
Z += np.bincount(I, minlength=len(Z))
print(Z)

[2. 4. 1. 3. 5. 2. 4. 6. 2. 1.]


#### 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? (★★★)

In [329]:
X = [1,2,3,4,5,6]
I = [1,3,9,3,4,1]
F = np.bincount(I,X)
print(F)

[0. 7. 0. 6. 5. 0. 0. 0. 0. 3.]


#### 66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors (★★☆)

In [330]:
w, h = 256, 256
I = np.random.randint(0, 4, (h, w, 3)).astype(np.ubyte)
colors = np.unique(I.reshape(-1, 3), axis=0)
n = len(colors)
print(n)

64


#### 67. Considering a four dimensions array, how to get sum over the last two axis at once? (★★★)

In [331]:
A = np.random.randint(0,10,(3,4,3,4))
mysum = A.sum(axis=(-2,-1))
print(mysum)

[[51 40 54 66]
 [52 63 76 67]
 [48 44 57 66]]


#### 68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset  indices? (★★★)

In [332]:
D = np.random.uniform(0,1,100)
S = np.random.randint(0,10,100)
D_sums = np.bincount(S, weights=D)
D_counts = np.bincount(S)
D_means = D_sums / D_counts
print(D_means)

[0.46833259 0.41549507 0.49784468 0.53563376 0.39676476 0.50221479
 0.43716565 0.36108269 0.5968298  0.64783794]


#### 69. How to get the diagonal of a dot product? (★★★)

In [333]:
A = np.random.uniform(0,1,(5,5))
B = np.random.uniform(0,1,(5,5))

np.einsum("ij,ji->i", A, B)

array([3.47327864, 0.56063639, 2.10723326, 1.95267663, 1.18312997])

#### 70. Consider the vector [1, 2, 3, 4, 5], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★)

In [334]:
vec = np.array([1, 2, 3, 4, 5])

n = len(vec)
ans = np.zeros((n + (n-1)*3))
ans[::4] = vec 

ans 

array([1., 0., 0., 0., 2., 0., 0., 0., 3., 0., 0., 0., 4., 0., 0., 0., 5.])

#### 71. Consider an array of dimension (5,5,3), how to multiply it by an array with dimensions (5,5)? (★★★)

In [335]:
A = np.random.random((5, 5, 3))
B = np.random.random((5,5))

np.einsum("ijk,ij->ijk", A, B)

# print(A * B[:,:,None])

array([[[0.11353682, 0.05649964, 0.06646454],
        [0.01829163, 0.13241168, 0.39407072],
        [0.15140766, 0.01392906, 0.09947728],
        [0.02894113, 0.01532366, 0.05609734],
        [0.06670809, 0.1331971 , 0.09149025]],

       [[0.0467539 , 0.01997005, 0.02869824],
        [0.10545391, 0.26005462, 0.34482465],
        [0.0161522 , 0.01650302, 0.02950562],
        [0.43635026, 0.2793682 , 0.32252986],
        [0.07307829, 0.14589973, 0.17889389]],

       [[0.40462167, 0.5114586 , 0.31986466],
        [0.13944056, 0.72752401, 0.61049152],
        [0.16267055, 0.0450411 , 0.09538754],
        [0.02781278, 0.00497094, 0.00478685],
        [0.13797861, 0.06100061, 0.15723346]],

       [[0.31187516, 0.53411327, 0.09278389],
        [0.13952885, 0.23040749, 0.10479811],
        [0.2477637 , 0.02624871, 0.02752961],
        [0.14691812, 0.10057637, 0.10996874],
        [0.26510371, 0.50710047, 0.10488198]],

       [[0.76995574, 0.0984098 , 0.7988819 ],
        [0.15385979, 0.172

#### 72. How to swap two rows of an array? (★★★)

In [336]:
A = np.arange(16).reshape(4, -1)

A[[2,3]] = A[[3,2]]

A

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [12, 13, 14, 15],
       [ 8,  9, 10, 11]])

#### 73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the  triangles (★★★)

In [337]:
faces = np.random.randint(0, 100, (10, 3))
F = np.roll(faces.repeat(2, axis=1), -1, axis=1).reshape(-1, 2)
F = np.sort(F, axis=1)              # undirected
unique_edges = np.unique(F, axis=0) # (K, 2) without structured dtype

#### 74. Given a sorted array C that corresponds to a bincount, how to produce an array A such that np.bincount(A) == C? (★★★)

In [338]:
C = np.bincount([1,1,2,3,4,4,6])
print(C)
A = np.repeat(np.arange(len(C)), C)
print(A)

[0 2 1 1 2 0 1]
[1 1 2 3 4 4 6]


#### 75. How to compute averages using a sliding window over an array? (★★★)

In [339]:
Z = np.arange(20)
n = 3 # window size 

# 1
a = np.cumsum(Z)
a[n:] = a[n:] - a[:-n]
ans = a[n - 1:] / n
ans

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12., 13.,
       14., 15., 16., 17., 18.])

In [340]:
np.lib.stride_tricks.sliding_window_view(Z, n).mean(axis=1)

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12., 13.,
       14., 15., 16., 17., 18.])

#### 76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z[0],Z[1],Z[2]) and each subsequent row is  shifted by 1 (last row should be (Z[-3],Z[-2],Z[-1]) (★★★)

In [341]:
z = np.arange(15)
np.lib.stride_tricks.sliding_window_view(z, 3)

array([[ 0,  1,  2],
       [ 1,  2,  3],
       [ 2,  3,  4],
       [ 3,  4,  5],
       [ 4,  5,  6],
       [ 5,  6,  7],
       [ 6,  7,  8],
       [ 7,  8,  9],
       [ 8,  9, 10],
       [ 9, 10, 11],
       [10, 11, 12],
       [11, 12, 13],
       [12, 13, 14]])

#### 77. How to negate a boolean, or to change the sign of a float inplace? (★★★)

In [342]:
Z = np.random.randint(0,2,100)
np.logical_not(Z, out=Z)

array([0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0,
       0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1,
       0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1,
       0, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1,
       0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1])

In [343]:
Z = np.random.uniform(-1.0,1.0,100)
np.negative(Z, out=Z)

array([-0.49719874,  0.15683619,  0.3577805 , -0.97511664,  0.72572116,
       -0.90001067, -0.57208014,  0.26919482, -0.75991184,  0.25988684,
       -0.92968117, -0.51958941,  0.22921731,  0.17476649,  0.24133715,
        0.03637767, -0.56059847, -0.599871  , -0.95718251, -0.7200249 ,
       -0.59753339,  0.91922167,  0.33770074, -0.80479097, -0.39351786,
       -0.56797505, -0.04769653,  0.81477897,  0.81984023, -0.96127451,
       -0.23285905,  0.19455723,  0.16756006, -0.26065324,  0.79783991,
        0.72538606,  0.92023003, -0.34479759, -0.09864527, -0.71849213,
        0.28012729,  0.50931036,  0.12173427, -0.90109774, -0.2671222 ,
        0.76441129,  0.48263734, -0.66891045,  0.268462  ,  0.23294896,
       -0.13186747, -0.03556202, -0.85354955,  0.56852279, -0.23048485,
        0.67170773, -0.03084738, -0.47932467, -0.25559844,  0.16358994,
        0.86558126, -0.78270749,  0.87123394,  0.24931943, -0.30460373,
        0.42510833,  0.47826873,  0.88716038,  0.70069491,  0.82

#### 78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i (P0[i],P1[i])? (★★★)

In [344]:
P0 = np.random.uniform(-10,10,(10,2))
P1 = np.random.uniform(-10,10,(10,2))
p  = np.random.uniform(-10,10,( 1,2))


diff = P1 - P0
diff2 = P0 - p 

np.abs(diff[:,0]*diff2[:,1] - diff[:,1]*diff2[:,0]) / np.linalg.norm(diff, axis=1)

array([ 2.73115624, 11.54558274,  9.94558276,  7.46599175,  3.07964647,
        3.67093242, 10.86765925,  1.14741059,  5.73191603,  8.88434093])

In [345]:
def distance_faster(P0,P1,p):
    #Author: Hemanth Pasupuleti
    #Reference: https://mathworld.wolfram.com/Point-LineDistance2-Dimensional.html

    v = P1- P0 
    v[:,[0,1]] = v[:,[1,0]]
    v[:,1]*=-1 
    norm = np.linalg.norm(v,axis=1)   
    r = P0 - p
    d = np.abs(np.einsum("ij,ij->i",r,v)) / norm 

    return d

print(distance_faster(P0, P1, p))

[ 2.73115624 11.54558274  9.94558276  7.46599175  3.07964647  3.67093242
 10.86765925  1.14741059  5.73191603  8.88434093]


#### 79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P[j]) to each line i (P0[i],P1[i])? (★★★)

In [346]:
P0 = np.random.uniform(-10,10,(10,2))
P1 = np.random.uniform(-10,10,(10,2))
p  = np.random.uniform(-10,10,( 15,2))

diff = P1 - P0 
diff2 = P0[:, None, :] - p[None, :, :]
diff2.shape

ans = np.abs(diff[:,0][:, None] * diff2[:, :, 1] - diff[:, 1][:, None] * diff2[:, :, 0]) / np.linalg.norm(diff, axis=1, keepdims=True)

In [347]:
def distance_points_to_lines(p: np.ndarray, p_1: np.ndarray, p_2: np.ndarray) -> np.ndarray:
    x_0, y_0 = p.T  # Shape -> (n points, )
    x_1, y_1 = p_1.T  # Shape -> (n lines, )
    x_2, y_2 = p_2.T  # Shape -> (n lines, )

    # Displacement vector coordinates from p_1 -> p_2
    dx = x_2 - x_1  # Shape -> (n lines, )
    dy = y_2 - y_1  # Shape -> (n lines, )

    # The 'cross product' term
    cross_term = x_2 * y_1 - y_2 * x_1  # Shape -> (n lines, )

    # Broadcast x_0, y_0 (n points, 1) and dx, dy, cross_term (1, n lines) -> (n points, n lines)
    numerator = np.abs(
        dy[np.newaxis, :] * x_0[:, np.newaxis]
        - dx[np.newaxis, :] * y_0[:, np.newaxis]
        + cross_term[np.newaxis, :]
    )
    denominator = np.sqrt(dx**2 + dy**2)  # Shape -> (n lines, )

    # Shape (n points, n lines) / (1, n_lines) -> (n points, n lines)
    return numerator / denominator[np.newaxis, :]

In [348]:
np.allclose(ans.T, distance_points_to_lines(p, P0, P1))

True

#### 80. Consider an arbitrary array, write a function that extracts a subpart with a fixed shape and centered on a given element (pad with a `fill` value when necessary) (★★★)

#### 81. Consider an array Z = [1,2,3,4,5,6,7,8,9,10,11,12,13,14], how to generate an array R = [[1,2,3,4], [2,3,4,5], [3,4,5,6], ..., [11,12,13,14]]? (★★★)

In [349]:
Z = [1,2,3,4,5,6,7,8,9,10,11,12,13,14]

np.lib.stride_tricks.sliding_window_view(Z, 4)

array([[ 1,  2,  3,  4],
       [ 2,  3,  4,  5],
       [ 3,  4,  5,  6],
       [ 4,  5,  6,  7],
       [ 5,  6,  7,  8],
       [ 6,  7,  8,  9],
       [ 7,  8,  9, 10],
       [ 8,  9, 10, 11],
       [ 9, 10, 11, 12],
       [10, 11, 12, 13],
       [11, 12, 13, 14]])

#### 82. Compute a matrix rank (★★★)

In [350]:
Z = np.random.random((1000,1000))
np.linalg.matrix_rank(Z)

1000

#### 83. How to find the most frequent value in an array?

In [351]:
Z = np.random.randint(0,10,50)
print(np.bincount(Z).argmax())

5


#### 84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix (★★★)

In [352]:
Z = np.arange(10*10).reshape(10,-1)

np.lib.stride_tricks.sliding_window_view(Z, (3,3))

array([[[[ 0,  1,  2],
         [10, 11, 12],
         [20, 21, 22]],

        [[ 1,  2,  3],
         [11, 12, 13],
         [21, 22, 23]],

        [[ 2,  3,  4],
         [12, 13, 14],
         [22, 23, 24]],

        [[ 3,  4,  5],
         [13, 14, 15],
         [23, 24, 25]],

        [[ 4,  5,  6],
         [14, 15, 16],
         [24, 25, 26]],

        [[ 5,  6,  7],
         [15, 16, 17],
         [25, 26, 27]],

        [[ 6,  7,  8],
         [16, 17, 18],
         [26, 27, 28]],

        [[ 7,  8,  9],
         [17, 18, 19],
         [27, 28, 29]]],


       [[[10, 11, 12],
         [20, 21, 22],
         [30, 31, 32]],

        [[11, 12, 13],
         [21, 22, 23],
         [31, 32, 33]],

        [[12, 13, 14],
         [22, 23, 24],
         [32, 33, 34]],

        [[13, 14, 15],
         [23, 24, 25],
         [33, 34, 35]],

        [[14, 15, 16],
         [24, 25, 26],
         [34, 35, 36]],

        [[15, 16, 17],
         [25, 26, 27],
         [35, 36, 37]],

    

#### 85. Create a 2D array subclass such that Z[i,j] == Z[j,i] (★★★)

#### 86. Consider a set of p matrices with shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1)) (★★★)

In [353]:
p = 68
n = 6

M = np.random.random((p,n,n))
V = np.random.random((p,n,1))

S = np.einsum('pij,pjk->ik', M, V)
print(S)

[[ 98.58002604]
 [106.41738551]
 [105.27370574]
 [ 96.92008635]
 [107.51563201]
 [107.88822291]]


In [354]:
S = np.tensordot(M, V, axes=[[0, 2], [0, 1]])
print(S)

[[ 98.58002604]
 [106.41738551]
 [105.27370574]
 [ 96.92008635]
 [107.51563201]
 [107.88822291]]


#### 87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)? (★★★)

In [355]:
Z = np.ones((16,16))

s0, s1 = Z.strides  # byte strides along each axis
Z_blocks = np.lib.stride_tricks.as_strided(
    Z,
    shape=(4, 4, 4, 4),          # (tiles_y, tiles_x, block_y, block_x)
    strides=(4*s0, 4*s1, s0, s1) # move 4 rows or cols between tiles
)

Z_blocks.sum((-2,-1))

array([[16., 16., 16., 16.],
       [16., 16., 16., 16.],
       [16., 16., 16., 16.],
       [16., 16., 16., 16.]])

#### 88. How to implement the Game of Life using numpy arrays? (★★★)


#### 89. How to get the n largest values of an array (★★★)

In [356]:
Z = np.arange(10000)
np.random.shuffle(Z)
n = 5

print (Z[np.argsort(Z)[-n:]])

[9995 9996 9997 9998 9999]


#### 90. Given an arbitrary number of vectors, build the cartesian product (every combination of every item) (★★★)

In [357]:
arrays = ([1, 2, 3], [4, 5], [6, 7])
arrays = [np.asarray(a) for a in arrays]
shape = (len(x) for x in arrays)
ix = np.indices(shape, dtype=int)
ix = ix.reshape(len(arrays), -1).T
for n, arr in enumerate(arrays):
    ix[:, n] = arrays[n][ix[:, n]]

ix

array([[1, 4, 6],
       [1, 4, 7],
       [1, 5, 6],
       [1, 5, 7],
       [2, 4, 6],
       [2, 4, 7],
       [2, 5, 6],
       [2, 5, 7],
       [3, 4, 6],
       [3, 4, 7],
       [3, 5, 6],
       [3, 5, 7]])

#### 91. How to create a record array from a regular array? (★★★)

#### 92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods (★★★)

In [358]:
x = np.random.rand(int(5e7))

%timeit np.power(x,3)
%timeit x*x*x
%timeit np.einsum('i,i,i->i',x,x,x)

356 ms ± 13.8 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
56.2 ms ± 868 μs per loop (mean ± std. dev. of 7 runs, 10 loops each)
60.1 ms ± 1.6 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


#### 93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B? (★★★)

In [359]:
a = np.arange(10)

b = np.array([2,3, 15])


a[:, None] == b

array([[False, False, False],
       [False, False, False],
       [ True, False, False],
       [False,  True, False],
       [False, False, False],
       [False, False, False],
       [False, False, False],
       [False, False, False],
       [False, False, False],
       [False, False, False]])

In [360]:
A = np.random.randint(0,5,(8,3))
B = np.random.randint(0,5,(2,2))

C = (A[..., np.newaxis, np.newaxis] == B)
# rows = np.where(C.any((3,1)).all(1))[0]
# print(rows)

In [361]:
C.shape

(8, 3, 2, 2)

In [362]:
C.any((3,1))

array([[ True, False],
       [False, False],
       [ True,  True],
       [ True, False],
       [False, False],
       [ True, False],
       [False, False],
       [ True, False]])

#### 94. Considering a 10x3 matrix, extract rows with unequal values (e.g. [2,2,3]) (★★★)

In [363]:
Z = np.random.randint(0,5,(10,3))


print(Z[np.all(Z[:, 1:] != Z[:, :-1], axis=1), :])
print("---")
print(Z[np.all(Z[:, 1:] == Z[:, :-1], axis=1), :])

[[1 2 0]
 [4 0 2]
 [2 3 0]
 [3 4 0]
 [4 0 4]
 [1 0 4]]
---
[]


#### 95. Convert a vector of ints into a matrix binary representation (★★★)

#### 96. Given a two dimensional array, how to extract unique rows? (★★★)

In [364]:
Z = np.random.randint(0,2,(6,3))
np.unique(Z, axis=0)

array([[0, 0, 0],
       [0, 0, 1],
       [1, 0, 0],
       [1, 1, 1]])

#### 97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function (★★★)

http://ajcr.net/Basic-guide-to-einsum/

In [365]:
A = np.random.uniform(0,1,10)
B = np.random.uniform(0,1,10)

np.einsum('i->', A)       # np.sum(A)
np.einsum('i,i->i', A, B) # A * B
np.einsum('i,i', A, B)    # np.inner(A, B)
np.einsum('i,j->ij', A, B)    # np.outer(A, B)

array([[0.14800376, 0.30930275, 0.41509194, 0.34968163, 0.4454637 ,
        0.43018293, 0.71611487, 0.49995162, 0.17090621, 0.30419212],
       [0.01869008, 0.0390591 , 0.05241828, 0.04415819, 0.05625366,
        0.05432399, 0.0904318 , 0.06313446, 0.02158223, 0.03841373],
       [0.15790301, 0.3299905 , 0.44285543, 0.37307014, 0.47525861,
        0.45895578, 0.76401232, 0.53339096, 0.1823373 , 0.32453806],
       [0.16116133, 0.33679984, 0.45199373, 0.38076842, 0.48506554,
        0.4684263 , 0.77977767, 0.54439745, 0.18609982, 0.33123488],
       [0.08443502, 0.17645487, 0.2368068 , 0.19949071, 0.25413366,
        0.24541609, 0.40853809, 0.2852186 , 0.09750069, 0.17353929],
       [0.0543764 , 0.11363745, 0.15250427, 0.1284726 , 0.16366282,
        0.15804868, 0.26309972, 0.18368161, 0.06279073, 0.11175981],
       [0.13889873, 0.29027478, 0.38955594, 0.3281696 , 0.41805926,
        0.40371854, 0.67206026, 0.46919514, 0.16039225, 0.28547855],
       [0.0555659 , 0.1161233 , 0.1558403

In [368]:
a = np.arange(6*7*8*9).reshape(6,7,8,9)
a[np.unravel_index(1621, (6,7,8,9))]

1621

In [375]:
B=10
C =3
H = 24
W = 24
temp = np.random.random((B, C, H, W))
mean = temp.mean(axis=1)
print(mean.shape)
std = temp.std(axis=1)

(temp - mean[:, None, ...]) / std[:, None, ...]

(10, 24, 24)


array([[[[-7.15234934e-01,  4.09337006e-01,  7.89723518e-01,
           9.93688489e-01,  8.61887005e-01,  5.53364104e-01,
          -5.23652860e-01, -1.17815047e+00, -1.39187341e+00,
           4.33425625e-01, -1.25785016e+00,  1.40792060e+00,
           1.40819039e+00, -1.13285719e+00,  3.43386758e-01,
           7.40896502e-01,  2.22016849e-01, -9.66415344e-01,
          -1.04925654e+00, -9.58718771e-01,  6.58918386e-01,
           9.78752341e-01,  1.41373243e+00,  1.01862961e+00],
         [-1.22388697e+00, -7.70268372e-01, -3.26330878e-01,
          -5.30314207e-01, -3.24195316e-01, -1.37902044e+00,
           3.17664626e-01,  6.24540984e-01,  1.29398407e+00,
           1.41287702e+00, -1.13293770e+00, -6.41733517e-01,
           9.90346671e-01,  1.04124771e+00, -1.18292595e+00,
          -1.29950790e+00, -7.12336384e-01, -8.90626146e-01,
          -2.39621522e-01,  5.90737744e-01,  8.26088067e-01,
           2.04904640e-01,  1.41269791e+00,  3.29590464e-01],
         [-9.99043903e